package models

import (
	"time"
)

// Workflow represents an AI agent workflow in the system
type Workflow struct {
	ID                   string     `json:"id" db:"id"`
	Name                 string     `json:"name" db:"name"`
	Description          *string    `json:"description,omitempty" db:"description"`
	ProductionVersionID  *string    `json:"production_version_id,omitempty" db:"production_version_id"`
	CreatedByUserID      string     `json:"created_by_user_id" db:"created_by_user_id"`
	CreatedAt            time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at" db:"updated_at"`
	IsLocked             bool       `json:"is_locked" db:"is_locked"`
	LockedByUserID       *string    `json:"locked_by_user_id,omitempty" db:"locked_by_user_id"`
	LockedAt             *time.Time `json:"locked_at,omitempty" db:"locked_at"`
}

// Version represents an immutable published snapshot of a workflow
type Version struct {
	ID                 string    `json:"id" db:"id"`
	WorkflowID         string    `json:"workflow_id" db:"workflow_id"`
	VersionNumber      int       `json:"version_number" db:"version_number"`
	DefinitionJSON     string    `json:"definition_json" db:"definition_json"` // Compiled definition.json
	PublishedByUserID  string    `json:"published_by_user_id" db:"published_by_user_id"`
	PublishedAt        time.Time `json:"published_at" db:"published_at"`
}

// SpecificationFile represents a markdown specification file for a version
type SpecificationFile struct {
	ID         string    `json:"id" db:"id"`
	VersionID  string    `json:"version_id" db:"version_id"`
	FilePath   string    `json:"file_path" db:"file_path"` // Relative path, e.g., "THE_CAST/Chief_Editor.md"
	Content    string    `json:"content" db:"content"`
	CreatedAt  time.Time `json:"created_at" db:"created_at"`
}

// Draft represents a work-in-progress set of changes based on a published version
type Draft struct {
	ID               string    `json:"id" db:"id"`
	WorkflowID       string    `json:"workflow_id" db:"workflow_id"`
	BasedOnVersionID *string   `json:"based_on_version_id,omitempty" db:"based_on_version_id"` // NULL for initial draft
	CreatedByUserID  string    `json:"created_by_user_id" db:"created_by_user_id"`
	CreatedAt        time.Time `json:"created_at" db:"created_at"`
	UpdatedAt        time.Time `json:"updated_at" db:"updated_at"`
}

// DraftSpecificationFile represents a specification file in a draft
type DraftSpecificationFile struct {
	ID        string    `json:"id" db:"id"`
	DraftID   string    `json:"draft_id" db:"draft_id"`
	FilePath  string    `json:"file_path" db:"file_path"` // Relative path
	Content   string    `json:"content" db:"content"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// Proposal represents a refinement proposal generated by the Builder Agent
type Proposal struct {
	ID                 string     `json:"id" db:"id"`
	DraftID            string     `json:"draft_id" db:"draft_id"`
	UserPrompt         string     `json:"user_prompt" db:"user_prompt"`
	ContextFilePath    *string    `json:"context_file_path,omitempty" db:"context_file_path"`
	ContextSelection   *string    `json:"context_selection,omitempty" db:"context_selection"`
	AIGeneratedContent string     `json:"ai_generated_content" db:"ai_generated_content"` // JSONB with proposed_changes, impact_analysis, etc.
	Status             string     `json:"status" db:"status"` // PENDING, APPROVED, REJECTED, FAILED
	ThreadID           *string    `json:"thread_id,omitempty" db:"thread_id"` // LangGraph thread ID
	ExecutionTrace     *string    `json:"execution_trace,omitempty" db:"execution_trace"` // Full execution trace (JSONB)
	CreatedByUserID    string     `json:"created_by_user_id" db:"created_by_user_id"`
	CreatedAt          time.Time  `json:"created_at" db:"created_at"`
	ResolvedByUserID   *string    `json:"resolved_by_user_id,omitempty" db:"resolved_by_user_id"`
	ResolvedAt         *time.Time `json:"resolved_at,omitempty" db:"resolved_at"`
}

// ProposalStatus represents the status of a proposal
type ProposalStatus string

const (
	ProposalStatusPending  ProposalStatus = "PENDING"
	ProposalStatusApproved ProposalStatus = "APPROVED"
	ProposalStatusRejected ProposalStatus = "REJECTED"
	ProposalStatusFailed   ProposalStatus = "FAILED"
)

// CreateWorkflowRequest represents the request to create a new workflow
type CreateWorkflowRequest struct {
	Name        string  `json:"name" binding:"required"`
	Description *string `json:"description,omitempty"`
}

// CreateWorkflowResponse represents the response after creating a workflow
type CreateWorkflowResponse struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
}

// GetWorkflowResponse represents the response for a single workflow
type GetWorkflowResponse struct {
	ID                  string     `json:"id"`
	Name                string     `json:"name"`
	Description         *string    `json:"description,omitempty"`
	ProductionVersionID *string    `json:"production_version_id,omitempty"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	IsLocked            bool       `json:"is_locked"`
	LockedByUserID      *string    `json:"locked_by_user_id,omitempty"`
	LockedAt            *time.Time `json:"locked_at,omitempty"`
	HasActiveDraft      bool       `json:"has_active_draft"`
}

// VersionResponse represents a version in API responses
type VersionResponse struct {
	ID            string    `json:"id"`
	WorkflowID    string    `json:"workflow_id"`
	VersionNumber int       `json:"version_number"`
	PublishedAt   time.Time `json:"published_at"`
	IsProduction  bool      `json:"is_production"`
}

// RefinementRequest represents a request to refine a workflow
type RefinementRequest struct {
	UserPrompt        string  `json:"user_prompt" binding:"required"`
	ContextFilePath   *string `json:"context_file_path,omitempty"`
	ContextSelection  *string `json:"context_selection,omitempty"`
}

// RefinementResponse represents the proposal generated from a refinement request
type RefinementResponse struct {
	ProposalID         string                 `json:"proposal_id"`
	ThreadID           string                 `json:"thread_id"` // LangGraph thread ID for WebSocket streaming
	Status             string                 `json:"status"` // "approved" or "denied"
	Reason             string                 `json:"reason,omitempty"`
	ProposedChanges    map[string]interface{} `json:"proposed_changes,omitempty"`
	ImpactAnalysis     string                 `json:"impact_analysis,omitempty"`
	Definition         map[string]interface{} `json:"definition,omitempty"`
	CreatedAt          time.Time              `json:"created_at"`
}

// ApproveProposalResponse represents the response after approving a proposal
type ApproveProposalResponse struct {
	ProposalID string    `json:"proposal_id"`
	ApprovedAt time.Time `json:"approved_at"`
	Message    string    `json:"message"`
}

// RejectProposalResponse represents the response after rejecting a proposal
type RejectProposalResponse struct {
	ProposalID string `json:"proposal_id"`
	Message    string `json:"message"`
}

// PublishDraftRequest represents a request to publish a draft
type PublishDraftRequest struct {
	VersionNotes *string `json:"version_notes,omitempty"`
}

// DeployVersionRequest represents a request to deploy a version to production
type DeployVersionRequest struct {
	VersionNumber int `json:"version_number" binding:"required"`
}
