apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ide-orchestrator-app-secrets
  namespace: intelligence-orchestrator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: ide-orchestrator-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPEC_ENGINE_URL
      remoteRef:
        key: /zerotouch/prod/ide-orchestrator/spec-engine-url