apiVersion: batch/v1
kind: Job
metadata:
  name: "{{JOB_NAME}}"
  namespace: "{{NAMESPACE}}"
  labels:
    app: ide-orchestrator-tests
    test-type: integration
    test-suite: "{{TEST_NAME}}"
spec:
  template:
    metadata:
      labels:
        app: ide-orchestrator-tests
        test-type: integration
        test-suite: "{{TEST_NAME}}"
    spec:
      containers:
      - name: test-runner
        image: "{{IMAGE}}"
        workingDir: /app
        env:
        # Database credentials from K8s secrets
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ide-orchestrator-db-conn
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ide-orchestrator-db-conn
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: ide-orchestrator-db-conn
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: ide-orchestrator-db-conn
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: ide-orchestrator-db-conn
              key: POSTGRES_PORT
        # Service dependencies
        - name: SPEC_ENGINE_URL
          value: "http://deepagents-runtime.intelligence-deepagents.svc:8080"
        # JWT configuration
        - name: JWT_SECRET
          value: "test-secret-key-for-integration-tests"
        # Test configuration
        - name: GO_ENV
          value: "test"
        command: 
        - "/bin/sh"
        - "-c"
        - |
          set -e  # Exit on any error
          set -o pipefail  # Exit on pipe failures
          
          echo "=============================================="
          echo "🚀 Starting in-cluster integration tests"
          echo "=============================================="
          echo "Test Path: {{TEST_PATH}}"
          echo "Test Name: {{TEST_NAME}}"
          echo "Timestamp: $(date)"
          echo ""
          
          echo "=== ENVIRONMENT CHECK ==="
          echo "Go version: $(go version)"
          echo "Working directory: $(pwd)"
          echo "Available disk space:"
          df -h /app || echo "Could not check disk space"
          echo ""
          
          echo "=== DEPENDENCY CHECK ==="
          echo "Checking database connectivity..."
          while ! nc -z "$POSTGRES_HOST" "$POSTGRES_PORT"; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "✅ PostgreSQL is ready"
          
          echo "Checking DeepAgents Runtime connectivity..."
          while ! nc -z deepagents-runtime.intelligence-deepagents.svc 8080; do
            echo "Waiting for DeepAgents Runtime to be ready..."
            sleep 2
          done
          echo "✅ DeepAgents Runtime is ready"
          echo ""
          
          echo "=== TEST PATH VALIDATION ==="
          if [ -f "{{TEST_PATH}}" ] || [ -d "{{TEST_PATH}}" ]; then
            echo "✅ Test path exists: {{TEST_PATH}}"
            if [ -d "{{TEST_PATH}}" ]; then
              echo "Test files in directory:"
              find "{{TEST_PATH}}" -name "*_test.go" | head -10
            fi
          else
            echo "❌ Test path does not exist: {{TEST_PATH}}"
            echo "Available files/directories:"
            ls -la . | head -10
            echo "Looking for test files:"
            find . -name "*_test.go" | head -10
            exit 1
          fi
          echo ""
          
          echo "=== ARTIFACTS DIRECTORY ==="
          mkdir -p artifacts
          if [ -d "artifacts" ] && [ -w "artifacts" ]; then
            echo "✅ Artifacts directory ready: $(pwd)/artifacts"
          else
            echo "❌ Cannot create or write to artifacts directory"
            ls -la . | grep artifacts || echo "No artifacts directory found"
            exit 1
          fi
          echo ""
          
          echo "=============================================="
          echo "🧪 Running Go tests..."
          echo "=============================================="
          
          # Run pre-compiled tests to avoid memory issues during compilation
          echo "Running pre-compiled integration tests..."
          
          if ./integration-tests -test.v -test.timeout=10m 2>&1 | tee artifacts/test-output.log; then
            GO_TEST_EXIT_CODE=0
            echo "✅ Go tests passed"
          else
            GO_TEST_EXIT_CODE=$?
            echo "❌ Go tests failed with exit code: $GO_TEST_EXIT_CODE"
          fi
          
          # Also generate JSON output for parsing (if test binary supports it)
          echo ""
          echo "Generating JSON test results..."
          ./integration-tests -test.v -test.timeout=10m -test.json > artifacts/test-results.json 2>/dev/null || echo "JSON output not supported by test binary"
          
          echo ""
          echo "=============================================="
          echo "📊 Test Execution Complete"
          echo "=============================================="
          echo "Go test exit code: $GO_TEST_EXIT_CODE"
          echo ""
          
          echo "=== ARTIFACTS GENERATED ==="
          if [ -d "artifacts" ]; then
            echo "Artifacts directory contents:"
            ls -la artifacts/ || echo "No artifacts generated"
            
            if [ -f "artifacts/test-results.json" ]; then
              echo ""
              echo "✅ Test results JSON generated"
              echo "File size: $(stat -c%s artifacts/test-results.json 2>/dev/null || echo 'unknown') bytes"
            else
              echo "❌ No test-results.json generated"
            fi
            
            if [ -f "artifacts/coverage.out" ]; then
              echo "✅ Coverage report generated"
              echo "Coverage summary:"
              go tool cover -func=artifacts/coverage.out | tail -1 || echo "Could not generate coverage summary"
            else
              echo "❌ No coverage.out generated"
            fi
          else
            echo "❌ No artifacts directory found"
          fi
          echo ""
          
          # Exit with go test's exit code
          if [ $GO_TEST_EXIT_CODE -eq 0 ]; then
            echo "✅ All tests completed successfully!"
          else
            echo "❌ Tests failed with exit code: $GO_TEST_EXIT_CODE"
          fi
          
          echo "=============================================="
          echo "🏁 Test execution finished"
          echo "=============================================="
          
          exit $GO_TEST_EXIT_CODE
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "1000m"
        volumeMounts:
        - name: artifacts
          mountPath: /app/artifacts
      volumes:
      - name: artifacts
        emptyDir: {}
      restartPolicy: Never
      serviceAccountName: default
  backoffLimit: 0  # Don't retry failed pods - fail fast
  ttlSecondsAfterFinished: 3600  # Keep job for 1 hour after completion for debugging