# Database migration job - runs before deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: ide-orchestrator-migrations
  namespace: intelligence-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      name: ide-orchestrator-migrations
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: ide-orchestrator:ci-test
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo "Starting database migrations..."
            cd /app
            chmod +x ./scripts/ci/run-migrations.sh
            ./scripts/ci/run-migrations.sh
            echo "Migrations completed successfully"
        envFrom:
        - secretRef:
            name: ide-orchestrator-db-conn
        env:
        - name: MIGRATION_DIR
          value: "/app/migrations"
        - name: POSTGRES_SCHEMA
          value: "public"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ghcr-pull-secret
  backoffLimit: 3
  activeDeadlineSeconds: 600  # 10 minutes timeout