// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@bizmatters.dev"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Authenticate user with email and password, returns JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User authentication",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "Invalidate JWT token (client should discard token)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/refresh": {
            "post": {
                "description": "Generate a new JWT token from an existing valid token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh JWT token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/refinements/{proposalId}/approve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Approve a proposal and apply its changes to the workflow draft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refinements"
                ],
                "summary": "Approve a refinement proposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proposal ID",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ApproveProposalResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/refinements/{proposalId}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reject a proposal without applying its changes to the workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refinements"
                ],
                "summary": "Reject a refinement proposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proposal ID",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.RejectProposalResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new AI workflow with name and optional description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Create a new workflow",
                "parameters": [
                    {
                        "description": "Workflow details",
                        "name": "workflow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.CreateWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.CreateWorkflowResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a workflow with its metadata, lock status, and draft status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Get workflow by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.GetWorkflowResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}/deploy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Set a specific version as the production version for a workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Deploy version to production",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Version to deploy",
                        "name": "deploy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.DeployVersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}/draft": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete the current draft and all its proposals without publishing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Discard workflow draft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Draft discarded successfully"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}/refinements": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Request AI-powered refinement of a workflow based on user prompt and optional context",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refinements"
                ],
                "summary": "Create a workflow refinement proposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Refinement request",
                        "name": "refinement",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.RefinementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.RefinementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "423": {
                        "description": "Workflow is locked by another user",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}/versions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all published versions for a workflow with production status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "List all versions of a workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.VersionResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new immutable version from the current workflow draft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Publish draft as new version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.VersionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}/versions/{versionNumber}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific version of a workflow by version number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Get specific version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version number",
                        "name": "versionNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.VersionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws/refinements/{thread_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "WebSocket endpoint to stream real-time progress from Builder Agent",
                "tags": [
                    "refinements"
                ],
                "summary": "Stream Builder Agent refinement progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "thread_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.ApproveProposalResponse": {
            "type": "object",
            "properties": {
                "approved_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "proposal_id": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.CreateWorkflowRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.CreateWorkflowResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.DeployVersionRequest": {
            "type": "object",
            "required": [
                "version_number"
            ],
            "properties": {
                "version_number": {
                    "type": "integer"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.GetWorkflowResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "has_active_draft": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "is_locked": {
                    "type": "boolean"
                },
                "locked_at": {
                    "type": "string"
                },
                "locked_by_user_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "production_version_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_oranger_agent-builder_ide-orchestrator_internal_models.UserInfo"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.RefinementRequest": {
            "type": "object",
            "required": [
                "user_prompt"
            ],
            "properties": {
                "context_file_path": {
                    "type": "string"
                },
                "context_selection": {
                    "type": "string"
                },
                "user_prompt": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.RefinementResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "definition": {
                    "type": "object",
                    "additionalProperties": true
                },
                "impact_analysis": {
                    "type": "string"
                },
                "proposal_id": {
                    "type": "string"
                },
                "proposed_changes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "description": "\"approved\" or \"denied\"",
                    "type": "string"
                },
                "thread_id": {
                    "description": "LangGraph thread ID for WebSocket streaming",
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.RejectProposalResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "proposal_id": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.UserInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_oranger_agent-builder_ide-orchestrator_internal_models.VersionResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_production": {
                    "type": "boolean"
                },
                "published_at": {
                    "type": "string"
                },
                "version_number": {
                    "type": "integer"
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "IDE Orchestrator API",
	Description:      "AI-powered workflow builder API for multi-agent orchestration\n\nThis API enables creation, refinement, and deployment of LangGraph-based AI workflows.\nFeatures include: workflow versioning, draft refinements, AI-powered proposals, and production deployment.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
